### ISSUE TITLE
Support for Billingo API 3.0.14 including Receipts

### ISSUE THREAD

**Issue by ptorok** [CodingSans/billingo-client#12]
Hi,
Are there any plans to update the client to add support for Receipts, introduced in API 3.0.14?
Thanks

**Comment by Lacka90** [comment]
Hello!

Thanks for reaching out. Yes, it's planned to support and I hope in this
week.

Have great day!
Lacka

**Comment by ptorok** [comment]
Hi, any update on this?
Thanks!

**Comment by Lacka90** [comment]
Released with v2.0.0, please open another issue if you miss something!
Thank you!
