### ISSUE TITLE
List invoices of a partner

### ISSUE THREAD

**Issue by bioarnold** [CodingSans/billingo-client#2]
Hi,

  It would be nice if this client could list the invoices of a given partner. Billingo API supports this via a querystring param of the /documents endpoint, however I could not find how to access this feature via this client.

Thanks,
Peter

**Comment by Lacka90** [comment]
Hello, sorry for the late answer @bioarnold. I will try take a look for that feature this week. Will notify you with an update.
Thanks for the report :)

**Comment by Lacka90** [comment]
@bioarnold new version released! thanks for the reporting

**Comment by bioarnold** [comment]
> @bioarnold new version released! thanks for the reporting

@Lacka90 Many thanks for this change! :)
